backend:
  name: github
  repo: j0l33n/my-blog
  branch: main
  site_domain: joleenterbasket.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Collection name
    label: "Blog"
    folder: "blog" # Folder where the blog posts are stored
    create: true # Allow creation of new posts via the CMS
    slug: "{{slug}}" # Slug format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
